imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_rest:
    routing_loader:
        default_format: json
        include_format: false
    body_converter:
        enabled: true
    body_listener:
        decoders:
            json: fos_rest.decoder.json
    format_listener:
        enabled: true
        rules:
            - { path: '^/api/v1/', priorities: ['json'], fallback_format: json, prefer_extension: true}
            - { path: '^/', priorities: ['json', 'html'], fallback_format: 'html' }
    serializer:
        serialize_null: true
    view:
        view_response_listener: 'force'
        templating_formats:
            html: false
    param_fetcher_listener: 'force'

nelmio_api_doc:
    sandbox:
        authentication:
            name: X-Auth-Token
            delivery: header # http
           # type:     bearer
        enabled:  true
        accept_type: application/json
        body_format:
            formats: [ form, json ]
            default_format: json
        request_format:
            formats: []
            method: accept_header
        entity_to_choice: false

jms_serializer:
    metadata:
        directories:
#            FOSUB:
#                namespace_prefix: 'FOS\UserBundle'
#                path: '%kernel.root_dir%/Resources/serializer/FOSUB'

fos_user:
    db_driver: orm
    firewall_name: api
    user_class: AppBundle\Entity\User\User
    service:
        mailer: fos_user.mailer.default
    from_email:
        address:     noreply@simpleapi.loc
        sender_name: Simpleapi
    registration:
        confirmation:
            enabled:    true
#            template: ImpulseAppBundle:User:confirmation.email.twig
    resetting:
        token_ttl: 86400

fos_oauth_server:
    db_driver: orm
    client_class:        AppBundle\Entity\OAuth\Client
    access_token_class:  AppBundle\Entity\OAuth\AccessToken
    refresh_token_class: AppBundle\Entity\OAuth\RefreshToken
    auth_code_class:     AppBundle\Entity\OAuth\AuthCode
    service:
        user_provider: fos_user.user_provider.username_email
        options:
            access_token_lifetime: 28800
